title: "Metaschema"
baseURL: https://pages.nist.gov/metaschema/
defaultContentLanguage: en
languages:
  en:
    lang: en
    languageName: English
    weight: 1
MetaDataFormat: "yaml"
theme: "uswds"
googleAnalytics: UA-42404149-54
canonifyurls: true
enableGitInfo: true
enableRobotsTXT: true
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
pygmentsUseClasses: true
params:
  header:
    project_shortname: "Metaschema"
    project_name: "Metaschema Schema Generation Framework"
  custom_css:
  contentRepoPath: https://github.com/usnistgov/metaschema/tree/master/docs/content
  searchAffiliate: oscal
menu:
  secondary:
  - name: Get involved
    url: /contribute/
  - name: Contact Us
    url: /contribute/contact/
  - name: Github
    url: https://github.com/usnistgov/metaschema
