title: "Metaschema"
baseURL: https://pages.nist.gov/metaschema/
relativeURLs: true
canonifyURLs: true
defaultContentLanguage: en
disableAliases: false
languageCode: "en-us"
languages:
  en:
    lang: en
    languageName: English
    weight: 1
MetaDataFormat: "yaml"
theme:
- "uswds-nist"
- "uswds"
googleAnalytics: UA-66610693-1
enableGitInfo: true
enableRobotsTXT: true
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
pygmentsUseClasses: true
markup:
  goldmark:
    extensions:
      typographer: false
    parser:
      autoHeadingID: true
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
params:
  header:
    project_shortname: "Metaschema"
    project_name: "Metaschema Information Modeling Framework"
  contentRepoPath: https://github.com/usnistgov/metaschema/tree/master/docs/content
  searchAffiliate: metaschema
  usabanner: true
menu:
  secondary:
  - name: Get involved
    url: /contribute/
  - name: Contact Us
    url: /contribute/contact/
  - name: Github
    url: https://github.com/usnistgov/metaschema
module:
  mounts:
  - source: static
    target: static
